package io.gelio.app.core.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.lerp
import androidx.compose.ui.graphics.luminance
import io.gelio.app.data.model.CuratedPalette

enum class BrandPaletteContext {
    NEUTRAL,
    DESIGN,
    TOURISM,
}

private val LockedNeutralBase = Color(0xFF444444)
private val LockedBrandDarkSurface = Color(0xFF5E6165)
private val LockedDesignAccent = Color(0xFFF58565)
private val LockedTourismAccent = Color(0xFF0086BD)

private data class SchemeTokens(
    val primary: Color,
    val onPrimary: Color,
    val primaryContainer: Color,
    val onPrimaryContainer: Color,
    val secondary: Color,
    val onSecondary: Color,
    val secondaryContainer: Color,
    val onSecondaryContainer: Color,
    val tertiary: Color,
    val onTertiary: Color,
    val tertiaryContainer: Color,
    val onTertiaryContainer: Color,
    val background: Color,
    val onBackground: Color,
    val surface: Color,
    val onSurface: Color,
    val surfaceVariant: Color,
    val onSurfaceVariant: Color,
    val surfaceContainerLowest: Color,
    val surfaceContainerLow: Color,
    val surfaceContainer: Color,
    val surfaceContainerHigh: Color,
    val surfaceContainerHighest: Color,
    val outline: Color,
    val outlineVariant: Color,
    val scrim: Color = Color(0xFF000000),
)

private data class AccentPalette(
    val light: SchemeTokens,
    val dark: SchemeTokens,
)

private val baselinePalette = AccentPalette(
    light = SchemeTokens(
        primary = Color(0xFF6750A4),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFEADDFF),
        onPrimaryContainer = Color(0xFF21005D),
        secondary = Color(0xFF625B71),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFE8DEF8),
        onSecondaryContainer = Color(0xFF1D192B),
        tertiary = Color(0xFF7D5260),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFFFD8E4),
        onTertiaryContainer = Color(0xFF31111D),
        background = Color(0xFFFFF7FE),
        onBackground = Color(0xFF1D1B20),
        surface = Color(0xFFFFF7FE),
        onSurface = Color(0xFF1D1B20),
        surfaceVariant = Color(0xFFE7E0EC),
        onSurfaceVariant = Color(0xFF49454F),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFF7F2FA),
        surfaceContainer = Color(0xFFF3EDF7),
        surfaceContainerHigh = Color(0xFFECE6F0),
        surfaceContainerHighest = Color(0xFFE6E0E9),
        outline = Color(0xFF79747E),
        outlineVariant = Color(0xFFCAC4D0),
    ),
    dark = SchemeTokens(
        primary = Color(0xFFD0BCFF),
        onPrimary = Color(0xFF381E72),
        primaryContainer = Color(0xFF4F378B),
        onPrimaryContainer = Color(0xFFEADDFF),
        secondary = Color(0xFFCCC2DC),
        onSecondary = Color(0xFF332D41),
        secondaryContainer = Color(0xFF4A4458),
        onSecondaryContainer = Color(0xFFE8DEF8),
        tertiary = Color(0xFFEFB8C8),
        onTertiary = Color(0xFF492532),
        tertiaryContainer = Color(0xFF633B48),
        onTertiaryContainer = Color(0xFFFFD8E4),
        background = Color(0xFF141218),
        onBackground = Color(0xFFE6E0E9),
        surface = Color(0xFF141218),
        onSurface = Color(0xFFE6E0E9),
        surfaceVariant = Color(0xFF49454F),
        onSurfaceVariant = Color(0xFFCAC4D0),
        surfaceContainerLowest = Color(0xFF0F0D13),
        surfaceContainerLow = Color(0xFF1D1B20),
        surfaceContainer = Color(0xFF211F26),
        surfaceContainerHigh = Color(0xFF2B2930),
        surfaceContainerHighest = Color(0xFF36343B),
        outline = Color(0xFF938F99),
        outlineVariant = Color(0xFF49454F),
    ),
)

private val rosePalette = AccentPalette(
    light = SchemeTokens(
        primary = Color(0xFF8B4A60),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFFD9E2),
        onPrimaryContainer = Color(0xFF3A071B),
        secondary = Color(0xFF75565E),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFFFD9E2),
        onSecondaryContainer = Color(0xFF2C151C),
        tertiary = Color(0xFF7B5634),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFFFDCC1),
        onTertiaryContainer = Color(0xFF2D1600),
        background = Color(0xFFFFF8F8),
        onBackground = Color(0xFF22191C),
        surface = Color(0xFFFFF8F8),
        onSurface = Color(0xFF22191C),
        surfaceVariant = Color(0xFFF3DDE2),
        onSurfaceVariant = Color(0xFF524348),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFFEF1F3),
        surfaceContainer = Color(0xFFFBECEF),
        surfaceContainerHigh = Color(0xFFF6E6E9),
        surfaceContainerHighest = Color(0xFFF0E0E3),
        outline = Color(0xFF847378),
        outlineVariant = Color(0xFFD6C2C7),
    ),
    dark = SchemeTokens(
        primary = Color(0xFFFFB1C5),
        onPrimary = Color(0xFF541D31),
        primaryContainer = Color(0xFF6E3348),
        onPrimaryContainer = Color(0xFFFFD9E2),
        secondary = Color(0xFFE4BDC5),
        onSecondary = Color(0xFF43292F),
        secondaryContainer = Color(0xFF5B3F46),
        onSecondaryContainer = Color(0xFFFFD9E2),
        tertiary = Color(0xFFEDBE94),
        onTertiary = Color(0xFF452A0C),
        tertiaryContainer = Color(0xFF5F4020),
        onTertiaryContainer = Color(0xFFFFDCC1),
        background = Color(0xFF1A1114),
        onBackground = Color(0xFFEFDFE2),
        surface = Color(0xFF1A1114),
        onSurface = Color(0xFFEFDFE2),
        surfaceVariant = Color(0xFF524348),
        onSurfaceVariant = Color(0xFFD6C2C7),
        surfaceContainerLowest = Color(0xFF140C0F),
        surfaceContainerLow = Color(0xFF23181B),
        surfaceContainer = Color(0xFF2A1D21),
        surfaceContainerHigh = Color(0xFF35272B),
        surfaceContainerHighest = Color(0xFF403237),
        outline = Color(0xFF9F8C91),
        outlineVariant = Color(0xFF524348),
    ),
)

private val terracottaPalette = AccentPalette(
    light = SchemeTokens(
        primary = Color(0xFF8A4D3A),
        onPrimary = Color(0xFFFFF8F6),
        primaryContainer = Color(0xFFFFDAD0),
        onPrimaryContainer = Color(0xFF35120A),
        secondary = Color(0xFF77574C),
        onSecondary = Color(0xFFFFF8F6),
        secondaryContainer = Color(0xFFFFDBD0),
        onSecondaryContainer = Color(0xFF2C160E),
        tertiary = Color(0xFF6E5F37),
        onTertiary = Color(0xFFFFF9EC),
        tertiaryContainer = Color(0xFFF7E3A8),
        onTertiaryContainer = Color(0xFF241B00),
        background = Color(0xFFFFF8F6),
        onBackground = Color(0xFF241917),
        surface = Color(0xFFFFF8F6),
        onSurface = Color(0xFF241917),
        surfaceVariant = Color(0xFFF1DED8),
        onSurfaceVariant = Color(0xFF56413B),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFFCF2EE),
        surfaceContainer = Color(0xFFF8ECE8),
        surfaceContainerHigh = Color(0xFFF2E6E1),
        surfaceContainerHighest = Color(0xFFECDDD7),
        outline = Color(0xFF89736B),
        outlineVariant = Color(0xFFD9C2BB),
    ),
    dark = SchemeTokens(
        primary = Color(0xFFFFB59F),
        onPrimary = Color(0xFF552111),
        primaryContainer = Color(0xFF713725),
        onPrimaryContainer = Color(0xFFFFDBD0),
        secondary = Color(0xFFE7BEB1),
        onSecondary = Color(0xFF442A22),
        secondaryContainer = Color(0xFF5D4036),
        onSecondaryContainer = Color(0xFFFFDBD0),
        tertiary = Color(0xFFDCC78D),
        onTertiary = Color(0xFF3C2F05),
        tertiaryContainer = Color(0xFF554618),
        onTertiaryContainer = Color(0xFFF9E3A7),
        background = Color(0xFF1A1110),
        onBackground = Color(0xFFF2DFDA),
        surface = Color(0xFF1F1614),
        onSurface = Color(0xFFFCEDE8),
        surfaceVariant = Color(0xFF56413B),
        onSurfaceVariant = Color(0xFFD9C2BB),
        surfaceContainerLowest = Color(0xFF140D0C),
        surfaceContainerLow = Color(0xFF241917),
        surfaceContainer = Color(0xFF2B201D),
        surfaceContainerHigh = Color(0xFF362825),
        surfaceContainerHighest = Color(0xFF41312E),
        outline = Color(0xFFA58D85),
        outlineVariant = Color(0xFF56413B),
    ),
)

private val oceanPalette = AccentPalette(
    light = SchemeTokens(
        primary = Color(0xFF006A6D),
        onPrimary = Color(0xFFF1FFFF),
        primaryContainer = Color(0xFF93F1F4),
        onPrimaryContainer = Color(0xFF002021),
        secondary = Color(0xFF356568),
        onSecondary = Color(0xFFF3FEFF),
        secondaryContainer = Color(0xFFB8EBEE),
        onSecondaryContainer = Color(0xFF002022),
        tertiary = Color(0xFF445F91),
        onTertiary = Color(0xFFF9FAFF),
        tertiaryContainer = Color(0xFFD9E2FF),
        onTertiaryContainer = Color(0xFF001944),
        background = Color(0xFFF2FBFB),
        onBackground = Color(0xFF151D1E),
        surface = Color(0xFFF4FCFC),
        onSurface = Color(0xFF151D1E),
        surfaceVariant = Color(0xFFD7E4E5),
        onSurfaceVariant = Color(0xFF3D494A),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFEEF7F7),
        surfaceContainer = Color(0xFFE8F2F2),
        surfaceContainerHigh = Color(0xFFE1ECEC),
        surfaceContainerHighest = Color(0xFFDBE6E6),
        outline = Color(0xFF6D797A),
        outlineVariant = Color(0xFFBEC8C9),
    ),
    dark = SchemeTokens(
        primary = Color(0xFF76D5D8),
        onPrimary = Color(0xFF003739),
        primaryContainer = Color(0xFF004F51),
        onPrimaryContainer = Color(0xFF97F1F4),
        secondary = Color(0xFFB7CCCD),
        onSecondary = Color(0xFF203536),
        secondaryContainer = Color(0xFF364B4D),
        onSecondaryContainer = Color(0xFFD2E8E9),
        tertiary = Color(0xFFBCC6F4),
        onTertiary = Color(0xFF102A59),
        tertiaryContainer = Color(0xFF2D4575),
        onTertiaryContainer = Color(0xFFD9E2FF),
        background = Color(0xFF0F1415),
        onBackground = Color(0xFFDDE5E6),
        surface = Color(0xFF131A1B),
        onSurface = Color(0xFFEAF2F2),
        surfaceVariant = Color(0xFF3D494A),
        onSurfaceVariant = Color(0xFFBEC8C9),
        surfaceContainerLowest = Color(0xFF0A0F10),
        surfaceContainerLow = Color(0xFF172021),
        surfaceContainer = Color(0xFF1E2829),
        surfaceContainerHigh = Color(0xFF293334),
        surfaceContainerHighest = Color(0xFF333E3F),
        outline = Color(0xFF879394),
        outlineVariant = Color(0xFF3D494A),
    ),
)

private val emeraldPalette = AccentPalette(
    light = SchemeTokens(
        primary = Color(0xFF2E6B49),
        onPrimary = Color(0xFFF4FFF6),
        primaryContainer = Color(0xFFB1F1C8),
        onPrimaryContainer = Color(0xFF042111),
        secondary = Color(0xFF4C6354),
        onSecondary = Color(0xFFF7FFF7),
        secondaryContainer = Color(0xFFCFE9D2),
        onSecondaryContainer = Color(0xFF0C1F13),
        tertiary = Color(0xFF396976),
        onTertiary = Color(0xFFF4FCFF),
        tertiaryContainer = Color(0xFFBDEAF9),
        onTertiaryContainer = Color(0xFF001F27),
        background = Color(0xFFF3FBF4),
        onBackground = Color(0xFF161D18),
        surface = Color(0xFFF5FDF6),
        onSurface = Color(0xFF161D18),
        surfaceVariant = Color(0xFFD9E5DA),
        onSurfaceVariant = Color(0xFF404942),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFEEF7EF),
        surfaceContainer = Color(0xFFE8F2E9),
        surfaceContainerHigh = Color(0xFFE2ECE3),
        surfaceContainerHighest = Color(0xFFDCE6DD),
        outline = Color(0xFF707971),
        outlineVariant = Color(0xFFC0C9C1),
    ),
    dark = SchemeTokens(
        primary = Color(0xFF95D4AB),
        onPrimary = Color(0xFF0B381F),
        primaryContainer = Color(0xFF1F5135),
        onPrimaryContainer = Color(0xFFB2F1C8),
        secondary = Color(0xFFB5CCB8),
        onSecondary = Color(0xFF203528),
        secondaryContainer = Color(0xFF374B3B),
        onSecondaryContainer = Color(0xFFD1E8D3),
        tertiary = Color(0xFFA6CFDC),
        onTertiary = Color(0xFF043542),
        tertiaryContainer = Color(0xFF224D59),
        onTertiaryContainer = Color(0xFFC2EBF8),
        background = Color(0xFF101512),
        onBackground = Color(0xFFDEE5DE),
        surface = Color(0xFF141A16),
        onSurface = Color(0xFFECF2EC),
        surfaceVariant = Color(0xFF404942),
        onSurfaceVariant = Color(0xFFC0C9C1),
        surfaceContainerLowest = Color(0xFF0B100D),
        surfaceContainerLow = Color(0xFF17201A),
        surfaceContainer = Color(0xFF1E2821),
        surfaceContainerHigh = Color(0xFF29332C),
        surfaceContainerHighest = Color(0xFF333D36),
        outline = Color(0xFF8A938B),
        outlineVariant = Color(0xFF404942),
    ),
)

private fun paletteFor(curatedPalette: CuratedPalette): AccentPalette = when (curatedPalette) {
    CuratedPalette.BASELINE -> baselinePalette
    CuratedPalette.ROSE -> rosePalette
    CuratedPalette.TERRACOTTA -> terracottaPalette
    CuratedPalette.OCEAN -> oceanPalette
    CuratedPalette.EMERALD -> emeraldPalette
}

fun showcaseBrandLightColorScheme(
    context: BrandPaletteContext,
    neutralBaseColor: String = "#444444",
): ColorScheme = brandLightTokens(context, neutralBaseColor).toLightColorScheme()

fun showcaseBrandDarkColorScheme(
    context: BrandPaletteContext,
    neutralBaseColor: String = "#444444",
): ColorScheme = brandDarkTokens(context, neutralBaseColor).toDarkColorScheme()

fun showcaseCuratedLightColorScheme(curatedPalette: CuratedPalette): ColorScheme =
    paletteFor(curatedPalette).light.toLightColorScheme()

fun showcaseCuratedDarkColorScheme(curatedPalette: CuratedPalette): ColorScheme =
    paletteFor(curatedPalette).dark.toDarkColorScheme()

private fun brandLightTokens(
    context: BrandPaletteContext,
    neutralBaseColor: String = "#444444",
): SchemeTokens {
    val resolvedNeutralBase = neutralBaseColor.toSafeNeutralBaseColor()
    return when (context) {
        BrandPaletteContext.NEUTRAL -> SchemeTokens(
            primary = Color(0xFF43464A),
            onPrimary = Color.White,
            primaryContainer = Color(0xFF484B50),
            onPrimaryContainer = Color.White,
            secondary = Color(0xFF4E5257),
            onSecondary = Color.White,
            secondaryContainer = Color(0xFF565A5F),
            onSecondaryContainer = Color.White,
            tertiary = Color(0xFF6B7177),
            onTertiary = Color.White,
            tertiaryContainer = Color(0xFF51555A),
            onTertiaryContainer = Color.White,
            background = resolvedNeutralBase,
            onBackground = Color.White,
            surface = lerp(resolvedNeutralBase, Color.Black, 0.10f),
            onSurface = Color.White,
            surfaceVariant = lerp(resolvedNeutralBase, Color.White, 0.18f),
            onSurfaceVariant = Color(0xFFF4F7FA),
            surfaceContainerLowest = lerp(resolvedNeutralBase, Color.Black, 0.28f),
            surfaceContainerLow = lerp(resolvedNeutralBase, Color.Black, 0.20f),
            surfaceContainer = lerp(resolvedNeutralBase, Color.Black, 0.12f),
            surfaceContainerHigh = lerp(resolvedNeutralBase, Color.White, 0.06f),
            surfaceContainerHighest = lerp(resolvedNeutralBase, Color.White, 0.12f),
            outline = Color(0xFFB7BCC2),
            outlineVariant = Color(0xFF8C9298),
        )

        BrandPaletteContext.DESIGN -> SchemeTokens(
            primary = LockedDesignAccent,
            onPrimary = Color(0xFF351C16),
            primaryContainer = Color(0xFFFFD8CE),
            onPrimaryContainer = Color(0xFF2A1511),
            secondary = Color(0xFFA5523F),
            onSecondary = Color.White,
            secondaryContainer = Color(0xFFFFC7B8),
            onSecondaryContainer = Color(0xFF321713),
            tertiary = Color(0xFF6E4E37),
            onTertiary = Color.White,
            tertiaryContainer = Color(0xFFF1D3BD),
            onTertiaryContainer = Color(0xFF27170E),
            background = LockedDesignAccent,
            onBackground = Color.White,
            surface = Color(0xFFFFF3EE),
            onSurface = Color(0xFF2B1A16),
            surfaceVariant = Color(0xFFF4C2B2),
            onSurfaceVariant = Color(0xFF5A423A),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFFFEEE7),
            surfaceContainer = Color(0xFFFFE3D8),
            surfaceContainerHigh = Color(0xFFFBCFC1),
            surfaceContainerHighest = Color(0xFFF4BBA8),
            outline = Color(0xFFA06C60),
            outlineVariant = Color(0xFFD6A294),
        )

        BrandPaletteContext.TOURISM -> SchemeTokens(
            primary = LockedTourismAccent,
            onPrimary = Color.White,
            primaryContainer = Color(0xFFBDEBFF),
            onPrimaryContainer = Color(0xFF06283B),
            secondary = Color(0xFF1B6785),
            onSecondary = Color.White,
            secondaryContainer = Color(0xFFB1E7FF),
            onSecondaryContainer = Color(0xFF05212F),
            tertiary = Color(0xFF365A7A),
            onTertiary = Color.White,
            tertiaryContainer = Color(0xFFD2E8F7),
            onTertiaryContainer = Color(0xFF0E2130),
            background = LockedTourismAccent,
            onBackground = Color.White,
            surface = Color(0xFFF1FAFF),
            onSurface = Color(0xFF102531),
            surfaceVariant = Color(0xFFC3E2F1),
            onSurfaceVariant = Color(0xFF3E5560),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFE9F7FF),
            surfaceContainer = Color(0xFFDDF1FB),
            surfaceContainerHigh = Color(0xFFCEE9F5),
            surfaceContainerHighest = Color(0xFFB9DCEC),
            outline = Color(0xFF628497),
            outlineVariant = Color(0xFFA8CCDB),
        )
    }
}

private fun brandDarkTokens(
    context: BrandPaletteContext,
    neutralBaseColor: String = "#444444",
): SchemeTokens {
    val resolvedNeutralBase = neutralBaseColor.toSafeNeutralBaseColor()
    return when (context) {
        BrandPaletteContext.NEUTRAL -> brandLightTokens(BrandPaletteContext.NEUTRAL, neutralBaseColor)

        BrandPaletteContext.DESIGN -> SchemeTokens(
            primary = LockedDesignAccent,
            onPrimary = Color(0xFF301913),
            primaryContainer = Color(0xFFD67659),
            onPrimaryContainer = Color(0xFF23120E),
            secondary = Color(0xFFFFC0AE),
            onSecondary = Color(0xFF351A15),
            secondaryContainer = Color(0xFF735852),
            onSecondaryContainer = Color(0xFFFFE0D5),
            tertiary = Color(0xFFF2D0B3),
            onTertiary = Color(0xFF342217),
            tertiaryContainer = Color(0xFF79625C),
            onTertiaryContainer = Color(0xFFFFE8D8),
            background = resolvedNeutralBase,
            onBackground = Color(0xFFF5F5F5),
            surface = lerp(resolvedNeutralBase, Color.White, 0.12f),
            onSurface = Color(0xFFF5F5F5),
            surfaceVariant = Color(0xFF75797E),
            onSurfaceVariant = Color(0xFFE1E3E5),
            surfaceContainerLowest = lerp(resolvedNeutralBase, Color.Black, 0.12f),
            surfaceContainerLow = lerp(resolvedNeutralBase, Color.Black, 0.05f),
            surfaceContainer = lerp(resolvedNeutralBase, Color.White, 0.08f),
            surfaceContainerHigh = lerp(resolvedNeutralBase, Color.White, 0.14f),
            surfaceContainerHighest = lerp(resolvedNeutralBase, Color.White, 0.18f),
            outline = Color(0xFFB2B4B7),
            outlineVariant = Color(0xFF7A7D81),
        )

        BrandPaletteContext.TOURISM -> SchemeTokens(
            primary = LockedTourismAccent,
            onPrimary = Color.White,
            primaryContainer = Color(0xFF2C9BCF),
            onPrimaryContainer = Color(0xFF081E2A),
            secondary = Color(0xFF95D7F2),
            onSecondary = Color(0xFF143244),
            secondaryContainer = Color(0xFF5B707C),
            onSecondaryContainer = Color(0xFFE6F6FD),
            tertiary = Color(0xFFC5DDF0),
            onTertiary = Color(0xFF173345),
            tertiaryContainer = Color(0xFF62717B),
            onTertiaryContainer = Color(0xFFF0FAFF),
            background = resolvedNeutralBase,
            onBackground = Color(0xFFF5F5F5),
            surface = lerp(resolvedNeutralBase, Color.White, 0.12f),
            onSurface = Color(0xFFF5F5F5),
            surfaceVariant = Color(0xFF727B82),
            onSurfaceVariant = Color(0xFFE1E5E8),
            surfaceContainerLowest = lerp(resolvedNeutralBase, Color.Black, 0.12f),
            surfaceContainerLow = lerp(resolvedNeutralBase, Color.Black, 0.05f),
            surfaceContainer = lerp(resolvedNeutralBase, Color.White, 0.08f),
            surfaceContainerHigh = lerp(resolvedNeutralBase, Color.White, 0.14f),
            surfaceContainerHighest = lerp(resolvedNeutralBase, Color.White, 0.18f),
            outline = Color(0xFFAFB6BC),
            outlineVariant = Color(0xFF787F84),
        )
    }
}

private fun String.toSafeNeutralBaseColor(): Color {
    val trimmed = trim().removePrefix("#")
    val hex = when {
        trimmed.length == 6 && trimmed.all { it.isDigit() || it.lowercaseChar() in 'a'..'f' } -> trimmed
        trimmed.length == 8 && trimmed.all { it.isDigit() || it.lowercaseChar() in 'a'..'f' } -> trimmed.drop(2)
        else -> return LockedNeutralBase
    }
    val color = Color(hex.toLong(16) or 0xFF000000)
    return if (color.luminance() <= 0.28f) color else lerp(color, Color.Black, 0.45f)
}

private fun SchemeTokens.toLightColorScheme(): ColorScheme =
    lightColorScheme(
        primary = primary,
        onPrimary = onPrimary,
        primaryContainer = primaryContainer,
        onPrimaryContainer = onPrimaryContainer,
        secondary = secondary,
        onSecondary = onSecondary,
        secondaryContainer = secondaryContainer,
        onSecondaryContainer = onSecondaryContainer,
        tertiary = tertiary,
        onTertiary = onTertiary,
        tertiaryContainer = tertiaryContainer,
        onTertiaryContainer = onTertiaryContainer,
        background = background,
        onBackground = onBackground,
        surface = surface,
        onSurface = onSurface,
        surfaceVariant = surfaceVariant,
        onSurfaceVariant = onSurfaceVariant,
        surfaceContainerLowest = surfaceContainerLowest,
        surfaceContainerLow = surfaceContainerLow,
        surfaceContainer = surfaceContainer,
        surfaceContainerHigh = surfaceContainerHigh,
        surfaceContainerHighest = surfaceContainerHighest,
        outline = outline,
        outlineVariant = outlineVariant,
        scrim = scrim,
    )

private fun SchemeTokens.toDarkColorScheme(): ColorScheme =
    darkColorScheme(
        primary = primary,
        onPrimary = onPrimary,
        primaryContainer = primaryContainer,
        onPrimaryContainer = onPrimaryContainer,
        secondary = secondary,
        onSecondary = onSecondary,
        secondaryContainer = secondaryContainer,
        onSecondaryContainer = onSecondaryContainer,
        tertiary = tertiary,
        onTertiary = onTertiary,
        tertiaryContainer = tertiaryContainer,
        onTertiaryContainer = onTertiaryContainer,
        background = background,
        onBackground = onBackground,
        surface = surface,
        onSurface = onSurface,
        surfaceVariant = surfaceVariant,
        onSurfaceVariant = onSurfaceVariant,
        surfaceContainerLowest = surfaceContainerLowest,
        surfaceContainerLow = surfaceContainerLow,
        surfaceContainer = surfaceContainer,
        surfaceContainerHigh = surfaceContainerHigh,
        surfaceContainerHighest = surfaceContainerHighest,
        outline = outline,
        outlineVariant = outlineVariant,
        scrim = scrim,
    )
